# Generated by Django 4.2.9 on 2024-01-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterpieces",
            name="pieces_name_en",
            field=models.CharField(default=1, max_length=64, verbose_name="英文名"),
            preserve_default=False,
        ),
    ]
