# Generated by Django 4.2.9 on 2024-01-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("culapp", "0002_masterpieces_pieces_name_en"),
    ]

    operations = [
        migrations.RenameField(
            model_name="masterpieces",
            old_name="pieces_name",
            new_name="pieces_name_ch",
        ),
    ]
