# Generated by Django 4.2.9 on 2024-01-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culapp", "0003_rename_pieces_name_masterpieces_pieces_name_ch"),
    ]

    operations = [
        migrations.RenameField(
            model_name="craftsman",
            old_name="craftsman_name",
            new_name="craftsman_name_ch",
        ),
        migrations.AddField(
            model_name="craftsman",
            name="craftsman_name_en",
            field=models.CharField(default=1, max_length=64, verbose_name="英文名"),
            preserve_default=False,
        ),
    ]
