# Generated by Django 4.2.9 on 2024-01-26 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culapp", "0005_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="partment",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="部门"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 26, 8, 16, 29, 797778, tzinfo=datetime.timezone.utc
                ),
                verbose_name="创建时间",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="姓名"
            ),
        ),
    ]
