# Generated by Django 4.2.9 on 2024-01-29 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("culapp", "0006_message_partment_alter_message_create_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                choices=[("SS", "传承人"), ("S", "群众")],
                default=1,
                max_length=64,
                verbose_name="职位",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 29, 7, 0, 2, 987795, tzinfo=datetime.timezone.utc
                ),
                verbose_name="创建时间",
            ),
        ),
    ]
